import { assertEquals } from "https://deno.land/std@0.153.0/testing/asserts.ts";
import calculatePoints from "./football.js";

Deno.test("calculatePoints", () => {
  assertEquals(
    calculatePoints([
      "1:0",
      "2:3",
      "3:1",
      "0:1",
      "7:1",
      "1:3",
      "3:2",
      "1:2",
      "2:0",
      "2:3",
    ]),
    30
  );
  assertEquals(
    calculatePoints([
      "2:3",
      "3:1",
      "0:1",
      "7:1",
      "1:3",
      "3:2",
      "1:2",
      "2:0",
      "2:3",
      "1:0",
    ]),
    0
  );
  assertEquals(
    calculatePoints([
      "1:1",
      "3:3",
      "3:2",
      "0:0",
      "1:1",
      "3:3",
      "2:2",
      "2:2",
      "2:2",
      "2:2",
    ]),
    10
  );
});
